[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Role of Strategic Thinking in Critical Thinking: Strategies for Planning and Executing Long-Term Goals Through Critical Thinking"
